Sylius\Component\Product\Model\ProductOption:
    exclusion_policy: ALL
    xml_root_name: product-option
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        code:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        position:
            expose: true
            type: integer
            groups: [Default, Detailed]
        values:
            expose: true
            type: iterable
            groups: [Default, Detailed]
        translations:
            expose: true
            type: iterable
            groups: [Default, Detailed]
    relations:
        -   rel: self
            href:
                route: sylius_admin_api_product_option_show
                parameters:
                    code: expr(object.getCode())
    virtual_properties:
        getName:
            serialized_name: name
            groups: [Default, Detailed, Autocomplete]
